name: Deploy to LiteSpeed Server

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
         cd /home/github/photo-editor
         git pull origin release  # Pull the latest code from the release branch.
         npm install  # Install/update project dependencies.
         ng build --prod --base-href /photo-app/  # Build the project for production with the specified base href.
