name: Deploy to LiteSpeed Server

on:
pull_request:
  branches:
    - release
push:
  branches:
    - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build project
        run: ng build --base-href /photo-app/
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/github/photo-editor
            git pull origin release  # Pull the latest code from the release branch.
            npm install  # Install/update project dependencies.
            ng build --base-href /photo-app/  # Build the project for production with the specified base href.
